config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  devise_scope :user do
    authenticated :user do
      root to: 'profiles#show', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end

    # temp signout route
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  resources :bookings
  resource :profile, only: [:show, :edit, :update]

  get 'my_bookings', to: 'bookings#my_bookings', as: 'my_bookings'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelBookingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'booking_validation', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dashboard</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbo-track': 'reload' %>

  <%= javascript_importmap_tags %>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 d-flex flex-column">
        <div class="card card-center flex-grow-1">
          <div class="card-body text-center">
            <div class="profile-img">
              <%= image_tag 'default_profile.jpg', class: 'img-fluid rounded-circle mb-3' %>
            </div>
            <h4 class="card-title"><%= current_user.name %></h4>
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to 'Profile', profile_path, class: "nav-link #{'active' if current_page?(profile_path)}" %></li>
              </li>
              <li class="nav-item">
                <%= link_to 'My Bookings', my_bookings_path, class: "nav-link #{'active' if current_page?(my_bookings_path)}" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-9 d-flex flex-column">
        <div class="card card-center flex-grow-1">
          <div class="card-body">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css' %>
  <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module' %>
  <%= javascript_include_tag 'booking_validation', 'data-turbo-track': 'reload', type: 'module' %>
  <%= javascript_include_tag "https://code.jquery.com/jquery-3.3.1.slim.min.js" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" %>
  <%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" %>
</body>
</html>